# Generated by Django 3.0.7 on 2020-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
