# Generated by Django 2.1.15 on 2020-06-27 06:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200627_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
