# Generated by Django 2.1.15 on 2020-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.TextField(default='test'),
        ),
    ]
