# Generated by Django 3.0.7 on 2020-06-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieComment',
            new_name='Comment',
        ),
    ]
